services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.local
        ports:
            - '8000:8000'
        environment:
            APP_ENV: local
            APP_DEBUG: 'true'
        volumes:
            - '.:/app'
            - './docker/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini'
